services:
  live-stream:
    image: 192.168.1.11:5000/live-stream:latest
    container_name: live-stream
    restart: always
    ports:
      - "8088:8088"
    volumes:
      # 配置文件
      - ./config.yaml:/app/config.yaml
      # 挂机视频所在文件夹
      - ./webcam:/app/webcam
      # 存放台标和所有叠加图片的文件夹
      - ./images:/app/images
      - ./progress.json:/app/progress.json
      - ./users.json:/app/users.json
    depends_on:
      - mediamtx

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: live-stream-mediamtx
    restart: always
    ports:
      - "8554:8554" # RTSP 推流接收端口
      - "1935:1935" # RTMP 推流接收端口 (备用)
      - "8888:8888" # HLS 查询端口
      - "8889:8889" # WebRTC 预览端口
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
