services:
  live-stream:
    image: 127.0.0.1:5000/live-stream:latest
    build: .
    container_name: live-stream
    restart: always
    ports:
      - "8088:8088"
    volumes:
      # 配置文件
      - /opt/docker/live-stream/config.yaml:/app/config.yaml
      # 挂机视频所在文件夹
      - /opt/docker/live-stream/webcam:/app/webcam
      # 存放台标和所有叠加图片的文件夹
      - /opt/docker/live-stream/images:/app/images
      - /opt/docker/live-stream/videos:/app/videos
      - /opt/docker/live-stream/progress.json:/app/progress.json
      - /opt/docker/live-stream/users.json:/app/users.json
    depends_on:
      - mediamtx

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: live-stream-mediamtx
    restart: always
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP (OBS 推流)
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC
    volumes:
      - /opt/docker/live-stream/mediamtx.yml:/mediamtx.yml
